-- MySQL Script generated by MySQL Workbench
-- Thu Aug 23 15:14:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema qdu
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `qdu` ;

-- -----------------------------------------------------
-- Schema qdu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qdu` DEFAULT CHARACTER SET utf8 ;
USE `qdu` ;

-- -----------------------------------------------------
-- Table `qdu`.`pics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `qdu`.`pics` ;

CREATE TABLE IF NOT EXISTS `qdu`.`pics` (
  `pic_id` BINARY(16) NOT NULL,
  `token` BINARY(16) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `clicks` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`pic_id`),
  UNIQUE INDEX `pic_id_UNIQUE` (`pic_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
